In [1]:
from pathlib import Path

import polars as pl
from morfeus import BuriedVolume, ConeAngle, Dispersion, Sterimol, XTB

import grrmlib as gl

In [2]:
gl.__version__

'0.1.1'

# 0. Featurization of MPAA

In [3]:
paths = sorted(Path("backbone").glob("*.com"))
rows = []

for path in paths:
    reader = gl.GaussianInputReader()
    mol = reader.read(path)
    xtb = XTB(
        mol.symbols,
        mol.atomcoords
    )
    ca = ConeAngle(
        mol.symbols,
        mol.atomcoords,
        atom_1=1,
        method="internal"
    )
    disp = Dispersion(
        mol.symbols,
        mol.atomcoords
    )
    row = {
        "backbone": int(path.stem),
        "backbone_homo": xtb.get_homo(),
        "backbone_lumo": xtb.get_lumo(),
        "backbone_ip": xtb.get_ip(),
        "backbone_ea": xtb.get_ea(),
        "backbone_cone_angle": ca.cone_angle
    }
    
    charges = xtb.get_charges()
    fukui_minus = xtb.get_fukui("nucleophilicity")
    fukui_zero = xtb.get_fukui("radical")
    fukui_plus = xtb.get_fukui("electrophilicity")
    polarizabilities = xtb.get_atom_polarizabilities()
    dipoles = xtb.get_atom_dipole_moments()
    p_ints = disp.atom_p_int
    
    labels = [1, 3, 7, 9]
    attached_indices = [7, 1, 1, 1]
    
    for label, attached_index in zip(labels, attached_indices):
        bv = BuriedVolume(
            mol.symbols,
            mol.atomcoords,
            metal_index=label
        )
        st = Sterimol(
            mol.symbols,
            mol.atomcoords,
            dummy_index=label,
            attached_index=attached_index
        )
        row_label = {
            f"backbone_charge_label{label}": charges[label],
            f"backbone_fukui_minus_label{label}": fukui_minus[label],
            f"backbone_fukui_zero_label{label}": fukui_zero[label],
            f"backbone_fukui_plus_label{label}": fukui_plus[label],
            f"backbone_polarizability_label{label}": polarizabilities[label],
            f"backbone_dipole_label{label}": dipoles[label],
            f"backbone_p_int_label{label}": p_ints[label],
            f"backbone_vbur_label{label}": bv.fraction_buried_volume * 100,
            f"backbone_B1_label{label}": st.B_1_value,
            f"backbone_B5_label{label}": st.B_5_value,
            f"backbone_L_label{label}": st.L_value,
        }
        row |= row_label
    
    rows.append(row)

df = pl.DataFrame(rows).sort("backbone")

In [4]:
df

shape: (8, 50)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ backbone ┆ backbone_ ┆ backbone_ ┆ backbone_ ┆ … ┆ backbone_ ┆ backbone_ ┆ backbone_ ┆ backbone_ │
│ ---      ┆ homo      ┆ lumo      ┆ ip        ┆   ┆ vbur_labe ┆ B1_label9 ┆ B5_label9 ┆ L_label9  │
│ i64      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ l9        ┆ ---       ┆ ---       ┆ ---       │
│          ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ f64       │
│          ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ -0.388311 ┆ -0.319427 ┆ 8.5047    ┆ … ┆ 43.766306 ┆ 2.1       ┆ 4.729343  ┆ 6.504397  │
│ 1        ┆ -0.384586 ┆ -0.317421 ┆ 8.314     ┆ … ┆ 44.016143 ┆ 2.1       ┆ 5.931428  ┆ 6.483278  │
│ 2        ┆ -0.381723 ┆ -0.314163 ┆ 7.9751    ┆ … ┆ 44.094763 ┆ 2.1       ┆ 8.459991  ┆ 6.488024  │
│ 3        ┆ -0.381061 ┆ -0.315206 ┆ 8.0633    ┆ … ┆ 44.726635 ┆ 2.1       ┆ 7.132493  ┆ 6.395848  │
│ 4        ┆ -0.380868 ┆ -0.315417 ┆ 7.9883    ┆ … ┆ 44.747601 ┆ 2.1       ┆ 7.687006  ┆ 6.387257  │
│ 5        ┆ -0.385259 ┆ -0.318421 ┆ 7.8419    ┆ … ┆ 44.093016 ┆ 2.1       ┆ 10.074941 ┆ 6.476354  │
│ 19       ┆ -0.377896 ┆ -0.312465 ┆ 7.9504    ┆ … ┆ 44.818067 ┆ 2.1       ┆ 7.15275   ┆ 6.373969  │
│ 20       ┆ -0.38298  ┆ -0.317786 ┆ 7.8691    ┆ … ┆ 44.498928 ┆ 2.1       ┆ 8.845057  ┆ 6.473576  │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
df.write_parquet("features_backbone.parquet")

# 1. Featurization of Pyridone

In [6]:
paths = sorted(Path("pyridone").glob("*.com"))
rows = []

for path in paths:
    reader = gl.GaussianInputReader()
    mol = reader.read(path)
    xtb = XTB(
        mol.symbols,
        mol.atomcoords
    )
    disp = Dispersion(
        mol.symbols,
        mol.atomcoords
    )
    row = {
        "pyridone": int(path.stem),
        "pyridone_homo": xtb.get_homo(),
        "pyridone_lumo": xtb.get_lumo(),
        "pyridone_ip": xtb.get_ip(),
        "pyridone_ea": xtb.get_ea(),
    }
    
    charges = xtb.get_charges()
    fukui_minus = xtb.get_fukui("nucleophilicity")
    fukui_zero = xtb.get_fukui("radical")
    fukui_plus = xtb.get_fukui("electrophilicity")
    polarizabilities = xtb.get_atom_polarizabilities()
    dipoles = xtb.get_atom_dipole_moments()
    p_ints = disp.atom_p_int
    
    labels = [1, 2, 3]
    attached_indices = [4, 1, 4]
    
    for label, attached_index in zip(labels, attached_indices):
        bv = BuriedVolume(
            mol.symbols,
            mol.atomcoords,
            metal_index=label
        )
        st = Sterimol(
            mol.symbols,
            mol.atomcoords,
            dummy_index=label,
            attached_index=attached_index
        )
        row_label = {
            f"pyridone_charge_label{label}": charges[label],
            f"pyridone_fukui_minus_label{label}": fukui_minus[label],
            f"pyridone_fukui_zero_label{label}": fukui_zero[label],
            f"pyridone_fukui_plus_label{label}": fukui_plus[label],
            f"pyridone_polarizability_label{label}": polarizabilities[label],
            f"pyridone_dipole_label{label}": dipoles[label],
            f"pyridone_p_int_label{label}": p_ints[label],
            f"pyridone_vbur_label{label}": bv.fraction_buried_volume * 100,
            f"pyridone_B1_label{label}": st.B_1_value,
            f"pyridone_B5_label{label}": st.B_5_value,
            f"pyridone_L_label{label}": st.L_value,
        }
        row |= row_label
    
    rows.append(row)

df = pl.DataFrame(rows)

In [7]:
df

shape: (13, 38)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ pyridone ┆ pyridone_ ┆ pyridone_ ┆ pyridone_ ┆ … ┆ pyridone_ ┆ pyridone_ ┆ pyridone_ ┆ pyridone_ │
│ ---      ┆ homo      ┆ lumo      ┆ ip        ┆   ┆ vbur_labe ┆ B1_label3 ┆ B5_label3 ┆ L_label3  │
│ i64      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ l3        ┆ ---       ┆ ---       ┆ ---       │
│          ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ f64       │
│          ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ -0.380848 ┆ -0.250706 ┆ 8.9152    ┆ … ┆ 45.716083 ┆ 1.7       ┆ 4.440932  ┆ 4.6939    │
│ 1        ┆ -0.406456 ┆ -0.280751 ┆ 8.7322    ┆ … ┆ 46.2804   ┆ 1.7       ┆ 5.622741  ┆ 5.957405  │
│ 10       ┆ -0.376059 ┆ -0.272477 ┆ 8.278     ┆ … ┆ 51.455344 ┆ 1.7       ┆ 5.706515  ┆ 4.698209  │
│ 11       ┆ -0.373141 ┆ -0.268191 ┆ 7.8267    ┆ … ┆ 51.731387 ┆ 1.7       ┆ 5.71321   ┆ 6.876921  │
│ 12       ┆ -0.377621 ┆ -0.2411   ┆ 8.2676    ┆ … ┆ 45.917001 ┆ 1.7       ┆ 4.449981  ┆ 6.792953  │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 5        ┆ -0.376779 ┆ -0.243526 ┆ 8.5306    ┆ … ┆ 45.869829 ┆ 1.825551  ┆ 4.43831   ┆ 5.727413  │
│ 6        ┆ -0.377388 ┆ -0.243575 ┆ 8.7115    ┆ … ┆ 45.664834 ┆ 1.7       ┆ 5.499003  ┆ 4.819833  │
│ 7        ┆ -0.376674 ┆ -0.246249 ┆ 8.527     ┆ … ┆ 46.012509 ┆ 1.7       ┆ 5.517145  ┆ 4.682176  │
│ 8        ┆ -0.375437 ┆ -0.243229 ┆ 8.5586    ┆ … ┆ 51.88688  ┆ 1.820742  ┆ 4.434857  ┆ 4.69404   │
│ 9        ┆ -0.377194 ┆ -0.266321 ┆ 8.1404    ┆ … ┆ 45.877399 ┆ 1.7       ┆ 5.693604  ┆ 6.84022   │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [8]:
df.write_parquet("features_pyridone.parquet")

# 2. Make Dataset

In [3]:
import polars as pl

df_backbone = pl.read_parquet("features_backbone.parquet")
df_pyridone = pl.read_parquet("features_pyridone.parquet")

In [4]:
df_X = df_backbone.join(df_pyridone, how="cross")

In [5]:
df_X

shape: (104, 88)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ backbone ┆ backbone_ ┆ backbone_ ┆ backbone_ ┆ … ┆ pyridone_ ┆ pyridone_ ┆ pyridone_ ┆ pyridone_ │
│ ---      ┆ homo      ┆ lumo      ┆ ip        ┆   ┆ vbur_labe ┆ B1_label3 ┆ B5_label3 ┆ L_label3  │
│ i64      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ l3        ┆ ---       ┆ ---       ┆ ---       │
│          ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ f64       │
│          ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ -0.388311 ┆ -0.319427 ┆ 8.5047    ┆ … ┆ 45.716083 ┆ 1.7       ┆ 4.440932  ┆ 4.6939    │
│ 0        ┆ -0.388311 ┆ -0.319427 ┆ 8.5047    ┆ … ┆ 46.2804   ┆ 1.7       ┆ 5.622741  ┆ 5.957405  │
│ 0        ┆ -0.388311 ┆ -0.319427 ┆ 8.5047    ┆ … ┆ 51.455344 ┆ 1.7       ┆ 5.706515  ┆ 4.698209  │
│ 0        ┆ -0.388311 ┆ -0.319427 ┆ 8.5047    ┆ … ┆ 51.731387 ┆ 1.7       ┆ 5.71321   ┆ 6.876921  │
│ 0        ┆ -0.388311 ┆ -0.319427 ┆ 8.5047    ┆ … ┆ 45.917001 ┆ 1.7       ┆ 4.449981  ┆ 6.792953  │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 20       ┆ -0.38298  ┆ -0.317786 ┆ 7.8691    ┆ … ┆ 45.869829 ┆ 1.825551  ┆ 4.43831   ┆ 5.727413  │
│ 20       ┆ -0.38298  ┆ -0.317786 ┆ 7.8691    ┆ … ┆ 45.664834 ┆ 1.7       ┆ 5.499003  ┆ 4.819833  │
│ 20       ┆ -0.38298  ┆ -0.317786 ┆ 7.8691    ┆ … ┆ 46.012509 ┆ 1.7       ┆ 5.517145  ┆ 4.682176  │
│ 20       ┆ -0.38298  ┆ -0.317786 ┆ 7.8691    ┆ … ┆ 51.88688  ┆ 1.820742  ┆ 4.434857  ┆ 4.69404   │
│ 20       ┆ -0.38298  ┆ -0.317786 ┆ 7.8691    ┆ … ┆ 45.877399 ┆ 1.7       ┆ 5.693604  ┆ 6.84022   │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [6]:
columns_feat = [col for col in df_X.columns if col not in ["pyridone", "backbone"]]
df_X = (
    df_X
    .select(["backbone", "pyridone"] + columns_feat)
    .sort(["pyridone", "backbone"])
)

In [7]:
df_X

shape: (104, 88)
┌──────────┬──────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ backbone ┆ pyridone ┆ backbone_h ┆ backbone_ ┆ … ┆ pyridone_ ┆ pyridone_ ┆ pyridone_ ┆ pyridone_ │
│ ---      ┆ ---      ┆ omo        ┆ lumo      ┆   ┆ vbur_labe ┆ B1_label3 ┆ B5_label3 ┆ L_label3  │
│ i64      ┆ i64      ┆ ---        ┆ ---       ┆   ┆ l3        ┆ ---       ┆ ---       ┆ ---       │
│          ┆          ┆ f64        ┆ f64       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ f64       │
│          ┆          ┆            ┆           ┆   ┆ f64       ┆           ┆           ┆           │
╞══════════╪══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ 0        ┆ -0.388311  ┆ -0.319427 ┆ … ┆ 45.716083 ┆ 1.7       ┆ 4.440932  ┆ 4.6939    │
│ 1        ┆ 0        ┆ -0.384586  ┆ -0.317421 ┆ … ┆ 45.716083 ┆ 1.7       ┆ 4.440932  ┆ 4.6939    │
│ 2        ┆ 0        ┆ -0.381723  ┆ -0.314163 ┆ … ┆ 45.716083 ┆ 1.7       ┆ 4.440932  ┆ 4.6939    │
│ 3        ┆ 0        ┆ -0.381061  ┆ -0.315206 ┆ … ┆ 45.716083 ┆ 1.7       ┆ 4.440932  ┆ 4.6939    │
│ 4        ┆ 0        ┆ -0.380868  ┆ -0.315417 ┆ … ┆ 45.716083 ┆ 1.7       ┆ 4.440932  ┆ 4.6939    │
│ …        ┆ …        ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 3        ┆ 12       ┆ -0.381061  ┆ -0.315206 ┆ … ┆ 45.917001 ┆ 1.7       ┆ 4.449981  ┆ 6.792953  │
│ 4        ┆ 12       ┆ -0.380868  ┆ -0.315417 ┆ … ┆ 45.917001 ┆ 1.7       ┆ 4.449981  ┆ 6.792953  │
│ 5        ┆ 12       ┆ -0.385259  ┆ -0.318421 ┆ … ┆ 45.917001 ┆ 1.7       ┆ 4.449981  ┆ 6.792953  │
│ 19       ┆ 12       ┆ -0.377896  ┆ -0.312465 ┆ … ┆ 45.917001 ┆ 1.7       ┆ 4.449981  ┆ 6.792953  │
│ 20       ┆ 12       ┆ -0.38298   ┆ -0.317786 ┆ … ┆ 45.917001 ┆ 1.7       ┆ 4.449981  ┆ 6.792953  │
└──────────┴──────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [8]:
df_y = pl.read_excel("combined.xlsx").sort(["pyridone", "backbone"])
df_y = df_y[["pyridone", "backbone", "alpha_av", "beta_av"]]
df_y = df_y.with_columns((pl.col("beta_av") / pl.col("alpha_av")).log().alias("beta_alpha"))

In [9]:
df_y

shape: (104, 5)
┌──────────┬──────────┬──────────┬───────────┬────────────┐
│ pyridone ┆ backbone ┆ alpha_av ┆ beta_av   ┆ beta_alpha │
│ ---      ┆ ---      ┆ ---      ┆ ---       ┆ ---        │
│ i64      ┆ i64      ┆ f64      ┆ f64       ┆ f64        │
╞══════════╪══════════╪══════════╪═══════════╪════════════╡
│ 0        ┆ 0        ┆ 4.114632 ┆ 51.388357 ┆ 2.524862   │
│ 0        ┆ 1        ┆ 3.998281 ┆ 51.539999 ┆ 2.556494   │
│ 0        ┆ 2        ┆ 3.428027 ┆ 47.832328 ┆ 2.635717   │
│ 0        ┆ 3        ┆ 3.636433 ┆ 47.845209 ┆ 2.576968   │
│ 0        ┆ 4        ┆ 3.323485 ┆ 43.960253 ┆ 2.582272   │
│ …        ┆ …        ┆ …        ┆ …         ┆ …          │
│ 12       ┆ 3        ┆ 3.583822 ┆ 46.114252 ┆ 2.554692   │
│ 12       ┆ 4        ┆ 3.742613 ┆ 49.74711  ┆ 2.587168   │
│ 12       ┆ 5        ┆ 1.175172 ┆ 48.959898 ┆ 3.729587   │
│ 12       ┆ 19       ┆ 3.338815 ┆ 41.066778 ┆ 2.509583   │
│ 12       ┆ 20       ┆ 2.762772 ┆ 23.601443 ┆ 2.145073   │
└──────────┴──────────┴──────────┴───────────┴────────────┘

In [10]:
df = df_X.join(df_y, on=["backbone", "pyridone"], how="left", maintain_order="left")

In [11]:
df

shape: (104, 91)
┌──────────┬──────────┬────────────┬────────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ backbone ┆ pyridone ┆ backbone_h ┆ backbone_l ┆ … ┆ pyridone_ ┆ alpha_av ┆ beta_av   ┆ beta_alph │
│ ---      ┆ ---      ┆ omo        ┆ umo        ┆   ┆ L_label3  ┆ ---      ┆ ---       ┆ a         │
│ i64      ┆ i64      ┆ ---        ┆ ---        ┆   ┆ ---       ┆ f64      ┆ f64       ┆ ---       │
│          ┆          ┆ f64        ┆ f64        ┆   ┆ f64       ┆          ┆           ┆ f64       │
╞══════════╪══════════╪════════════╪════════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ 0        ┆ 0        ┆ -0.388311  ┆ -0.319427  ┆ … ┆ 4.6939    ┆ 4.114632 ┆ 51.388357 ┆ 2.524862  │
│ 1        ┆ 0        ┆ -0.384586  ┆ -0.317421  ┆ … ┆ 4.6939    ┆ 3.998281 ┆ 51.539999 ┆ 2.556494  │
│ 2        ┆ 0        ┆ -0.381723  ┆ -0.314163  ┆ … ┆ 4.6939    ┆ 3.428027 ┆ 47.832328 ┆ 2.635717  │
│ 3        ┆ 0        ┆ -0.381061  ┆ -0.315206  ┆ … ┆ 4.6939    ┆ 3.636433 ┆ 47.845209 ┆ 2.576968  │
│ 4        ┆ 0        ┆ -0.380868  ┆ -0.315417  ┆ … ┆ 4.6939    ┆ 3.323485 ┆ 43.960253 ┆ 2.582272  │
│ …        ┆ …        ┆ …          ┆ …          ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ 3        ┆ 12       ┆ -0.381061  ┆ -0.315206  ┆ … ┆ 6.792953  ┆ 3.583822 ┆ 46.114252 ┆ 2.554692  │
│ 4        ┆ 12       ┆ -0.380868  ┆ -0.315417  ┆ … ┆ 6.792953  ┆ 3.742613 ┆ 49.74711  ┆ 2.587168  │
│ 5        ┆ 12       ┆ -0.385259  ┆ -0.318421  ┆ … ┆ 6.792953  ┆ 1.175172 ┆ 48.959898 ┆ 3.729587  │
│ 19       ┆ 12       ┆ -0.377896  ┆ -0.312465  ┆ … ┆ 6.792953  ┆ 3.338815 ┆ 41.066778 ┆ 2.509583  │
│ 20       ┆ 12       ┆ -0.38298   ┆ -0.317786  ┆ … ┆ 6.792953  ┆ 2.762772 ┆ 23.601443 ┆ 2.145073  │
└──────────┴──────────┴────────────┴────────────┴───┴───────────┴──────────┴───────────┴───────────┘

In [12]:
df.write_parquet("dataset.parquet")