In [1]:
import polars as pl

df_X = pl.read_csv("X.csv")

In [2]:
df_X

shape: (104, 54)
┌──────────┬──────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ backbone ┆ pyridone ┆ 0          ┆ 2         ┆ … ┆ 597       ┆ 602       ┆ 605       ┆ 642       │
│ ---      ┆ ---      ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ i64      ┆ i64      ┆ f64        ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞══════════╪══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ 0        ┆ -1542.9683 ┆ -1542.977 ┆ … ┆ -1543.059 ┆ -1543.047 ┆ -1543.056 ┆ -1543.057 │
│          ┆          ┆ 56         ┆ 051       ┆   ┆ 923       ┆ 561       ┆ 282       ┆ 803       │
│ 0        ┆ 1        ┆ -2461.8937 ┆ -2461.902 ┆ … ┆ -2461.982 ┆ -2461.969 ┆ -2461.979 ┆ -2461.980 │
│          ┆          ┆ 16         ┆ 411       ┆   ┆ 738       ┆ 7         ┆ 264       ┆ 786       │
│ 0        ┆ 2        ┆ -1879.7556 ┆ -1879.764 ┆ … ┆ -1879.845 ┆ -1879.834 ┆ -1879.842 ┆ -1879.843 │
│          ┆          ┆ 84         ┆ 379       ┆   ┆ 549       ┆ 163       ┆ 077       ┆ 541       │
│ 0        ┆ 3        ┆ -1747.3140 ┆ -1747.322 ┆ … ┆ -1747.403 ┆ -1747.392 ┆ -1747.399 ┆ -1747.401 │
│          ┆          ┆ 59         ┆ 754       ┆   ┆ 035       ┆ 222       ┆ 64        ┆ 236       │
│ 0        ┆ 4        ┆ -1770.6802 ┆ -1770.688 ┆ … ┆ -1770.770 ┆ -1770.759 ┆ -1770.767 ┆ -1770.769 │
│          ┆          ┆ 19         ┆ 914       ┆   ┆ 998       ┆ 206       ┆ 301       ┆ 056       │
│ …        ┆ …        ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 20       ┆ 8        ┆ -1813.1502 ┆ -1813.159 ┆ … ┆ -1813.231 ┆ -1813.223 ┆ -1813.233 ┆ -1813.233 │
│          ┆          ┆ 61         ┆ 029       ┆   ┆ 325       ┆ 553       ┆ 53        ┆ 366       │
│ 20       ┆ 9        ┆ -1927.3945 ┆ -1927.403 ┆ … ┆ -1927.479 ┆ -1927.473 ┆ -1927.482 ┆ -1927.483 │
│          ┆          ┆ 44         ┆ 311       ┆   ┆ 713       ┆ 892       ┆ 355       ┆ 028       │
│ 20       ┆ 10       ┆ -1927.3960 ┆ -1927.404 ┆ … ┆ -1927.477 ┆ -1927.470 ┆ -1927.479 ┆ -1927.479 │
│          ┆          ┆ 82         ┆ 849       ┆   ┆ 578       ┆ 162       ┆ 681       ┆ 933       │
│ 20       ┆ 11       ┆ -2080.9351 ┆ -2080.943 ┆ … ┆ -2081.016 ┆ -2081.009 ┆ -2081.018 ┆ -2081.018 │
│          ┆          ┆ 1          ┆ 877       ┆   ┆ 457       ┆ 478       ┆ 556       ┆ 933       │
│ 20       ┆ 12       ┆ -1888.2900 ┆ -1888.298 ┆ … ┆ -1888.374 ┆ -1888.366 ┆ -1888.376 ┆ -1888.377 │
│          ┆          ┆ 27         ┆ 794       ┆   ┆ 249       ┆ 643       ┆ 827       ┆ 997       │
└──────────┴──────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [3]:
df_y = pl.read_csv("y.csv")

In [4]:
df_y

shape: (104, 3)
┌──────────┬──────────┬───────────┐
│ backbone ┆ pyridone ┆ beta_av   │
│ ---      ┆ ---      ┆ ---       │
│ i64      ┆ i64      ┆ f64       │
╞══════════╪══════════╪═══════════╡
│ 0        ┆ 0        ┆ 51.388357 │
│ 0        ┆ 1        ┆ 63.841924 │
│ 0        ┆ 2        ┆ 59.085161 │
│ 0        ┆ 3        ┆ 53.059721 │
│ 0        ┆ 4        ┆ 53.917807 │
│ …        ┆ …        ┆ …         │
│ 20       ┆ 8        ┆ 19.228094 │
│ 20       ┆ 9        ┆ 24.595903 │
│ 20       ┆ 10       ┆ 21.060263 │
│ 20       ┆ 11       ┆ 19.203989 │
│ 20       ┆ 12       ┆ 23.601443 │
└──────────┴──────────┴───────────┘

In [5]:
df = df_X.join(df_y, on=["backbone", "pyridone"], how="left", maintain_order="left")

In [6]:
df

shape: (104, 55)
┌──────────┬──────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ backbone ┆ pyridone ┆ 0          ┆ 2         ┆ … ┆ 602       ┆ 605       ┆ 642       ┆ beta_av   │
│ ---      ┆ ---      ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ i64      ┆ i64      ┆ f64        ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞══════════╪══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ 0        ┆ -1542.9683 ┆ -1542.977 ┆ … ┆ -1543.047 ┆ -1543.056 ┆ -1543.057 ┆ 51.388357 │
│          ┆          ┆ 56         ┆ 051       ┆   ┆ 561       ┆ 282       ┆ 803       ┆           │
│ 0        ┆ 1        ┆ -2461.8937 ┆ -2461.902 ┆ … ┆ -2461.969 ┆ -2461.979 ┆ -2461.980 ┆ 63.841924 │
│          ┆          ┆ 16         ┆ 411       ┆   ┆ 7         ┆ 264       ┆ 786       ┆           │
│ 0        ┆ 2        ┆ -1879.7556 ┆ -1879.764 ┆ … ┆ -1879.834 ┆ -1879.842 ┆ -1879.843 ┆ 59.085161 │
│          ┆          ┆ 84         ┆ 379       ┆   ┆ 163       ┆ 077       ┆ 541       ┆           │
│ 0        ┆ 3        ┆ -1747.3140 ┆ -1747.322 ┆ … ┆ -1747.392 ┆ -1747.399 ┆ -1747.401 ┆ 53.059721 │
│          ┆          ┆ 59         ┆ 754       ┆   ┆ 222       ┆ 64        ┆ 236       ┆           │
│ 0        ┆ 4        ┆ -1770.6802 ┆ -1770.688 ┆ … ┆ -1770.759 ┆ -1770.767 ┆ -1770.769 ┆ 53.917807 │
│          ┆          ┆ 19         ┆ 914       ┆   ┆ 206       ┆ 301       ┆ 056       ┆           │
│ …        ┆ …        ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 20       ┆ 8        ┆ -1813.1502 ┆ -1813.159 ┆ … ┆ -1813.223 ┆ -1813.233 ┆ -1813.233 ┆ 19.228094 │
│          ┆          ┆ 61         ┆ 029       ┆   ┆ 553       ┆ 53        ┆ 366       ┆           │
│ 20       ┆ 9        ┆ -1927.3945 ┆ -1927.403 ┆ … ┆ -1927.473 ┆ -1927.482 ┆ -1927.483 ┆ 24.595903 │
│          ┆          ┆ 44         ┆ 311       ┆   ┆ 892       ┆ 355       ┆ 028       ┆           │
│ 20       ┆ 10       ┆ -1927.3960 ┆ -1927.404 ┆ … ┆ -1927.470 ┆ -1927.479 ┆ -1927.479 ┆ 21.060263 │
│          ┆          ┆ 82         ┆ 849       ┆   ┆ 162       ┆ 681       ┆ 933       ┆           │
│ 20       ┆ 11       ┆ -2080.9351 ┆ -2080.943 ┆ … ┆ -2081.009 ┆ -2081.018 ┆ -2081.018 ┆ 19.203989 │
│          ┆          ┆ 1          ┆ 877       ┆   ┆ 478       ┆ 556       ┆ 933       ┆           │
│ 20       ┆ 12       ┆ -1888.2900 ┆ -1888.298 ┆ … ┆ -1888.366 ┆ -1888.376 ┆ -1888.377 ┆ 23.601443 │
│          ┆          ┆ 27         ┆ 794       ┆   ┆ 643       ┆ 827       ┆ 997       ┆           │
└──────────┴──────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [7]:
for column in df.columns:
    if column.isnumeric() and column != "0":
        df = df.with_columns((pl.col(column) - pl.col("0")).alias(f"{column}_zero"))

In [8]:
df = df.with_columns((pl.col("beta_av") / (100 - pl.col("beta_av"))).log().alias("beta_av_logit"))

In [9]:
df = df.sort(["pyridone", "backbone"])

In [10]:
df

shape: (104, 107)
┌──────────┬──────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ backbone ┆ pyridone ┆ 0          ┆ 2         ┆ … ┆ 602_zero  ┆ 605_zero  ┆ 642_zero  ┆ beta_av_l │
│ ---      ┆ ---      ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ogit      │
│ i64      ┆ i64      ┆ f64        ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---       │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ f64       │
╞══════════╪══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ 0        ┆ -1542.9683 ┆ -1542.977 ┆ … ┆ -0.079205 ┆ -0.087926 ┆ -0.089446 ┆ 0.055549  │
│          ┆          ┆ 56         ┆ 051       ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 0        ┆ -1582.2585 ┆ -1582.267 ┆ … ┆ -0.07891  ┆ -0.085736 ┆ -0.087081 ┆ 0.061619  │
│          ┆          ┆ 95         ┆ 564       ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 0        ┆ -1700.1129 ┆ -1700.121 ┆ … ┆ -0.080326 ┆ -0.087646 ┆ -0.08901  ┆ -0.086761 │
│          ┆          ┆ 5          ┆ 83        ┆   ┆           ┆           ┆           ┆           │
│ 3        ┆ 0        ┆ -1660.8285 ┆ -1660.837 ┆ … ┆ -0.078678 ┆ -0.086442 ┆ -0.086987 ┆ -0.086245 │
│          ┆          ┆ 3          ┆ 468       ┆   ┆           ┆           ┆           ┆           │
│ 4        ┆ 0        ┆ -1700.1125 ┆ -1700.121 ┆ … ┆ -0.078223 ┆ -0.086452 ┆ -0.088093 ┆ -0.242775 │
│          ┆          ┆ 39         ┆ 489       ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …        ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 3        ┆ 12       ┆ -1775.2608 ┆ -1775.269 ┆ … ┆ -0.078144 ┆ -0.087104 ┆ -0.087674 ┆ -0.155744 │
│          ┆          ┆ 05         ┆ 743       ┆   ┆           ┆           ┆           ┆           │
│ 4        ┆ 12       ┆ -1814.5448 ┆ -1814.553 ┆ … ┆ -0.077692 ┆ -0.087091 ┆ -0.088991 ┆ -0.010116 │
│          ┆          ┆ 14         ┆ 764       ┆   ┆           ┆           ┆           ┆           │
│ 5        ┆ 12       ┆ -1927.5776 ┆ -1927.587 ┆ … ┆ -0.078492 ┆ -0.086451 ┆ -0.087795 ┆ -0.04161  │
│          ┆          ┆ 54         ┆ 112       ┆   ┆           ┆           ┆           ┆           │
│ 19       ┆ 12       ┆ -1814.5423 ┆ -1814.551 ┆ … ┆ -0.079794 ┆ -0.088365 ┆ -0.090207 ┆ -0.361206 │
│          ┆          ┆ 29         ┆ 514       ┆   ┆           ┆           ┆           ┆           │
│ 20       ┆ 12       ┆ -1888.2900 ┆ -1888.298 ┆ … ┆ -0.076616 ┆ -0.0868   ┆ -0.08797  ┆ -1.174656 │
│          ┆          ┆ 27         ┆ 794       ┆   ┆           ┆           ┆           ┆           │
└──────────┴──────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [11]:
df.write_parquet("dataset.parquet")