In [1]:
file = "001_fit"

In [2]:
import polars as pl

df = pl.read_parquet("../../dataset.parquet")

In [3]:
df

shape: (104, 107)
┌──────────┬──────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ backbone ┆ pyridone ┆ 0          ┆ 2         ┆ … ┆ 602_zero  ┆ 605_zero  ┆ 642_zero  ┆ beta_av_l │
│ ---      ┆ ---      ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ogit      │
│ i64      ┆ i64      ┆ f64        ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---       │
│          ┆          ┆            ┆           ┆   ┆           ┆           ┆           ┆ f64       │
╞══════════╪══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ 0        ┆ -1542.9683 ┆ -1542.977 ┆ … ┆ -0.079205 ┆ -0.087926 ┆ -0.089446 ┆ 0.055549  │
│          ┆          ┆ 56         ┆ 051       ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 0        ┆ -1582.2585 ┆ -1582.267 ┆ … ┆ -0.07891  ┆ -0.085736 ┆ -0.087081 ┆ 0.061619  │
│          ┆          ┆ 95         ┆ 564       ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 0        ┆ -1700.1129 ┆ -1700.121 ┆ … ┆ -0.080326 ┆ -0.087646 ┆ -0.08901  ┆ -0.086761 │
│          ┆          ┆ 5          ┆ 83        ┆   ┆           ┆           ┆           ┆           │
│ 3        ┆ 0        ┆ -1660.8285 ┆ -1660.837 ┆ … ┆ -0.078678 ┆ -0.086442 ┆ -0.086987 ┆ -0.086245 │
│          ┆          ┆ 3          ┆ 468       ┆   ┆           ┆           ┆           ┆           │
│ 4        ┆ 0        ┆ -1700.1125 ┆ -1700.121 ┆ … ┆ -0.078223 ┆ -0.086452 ┆ -0.088093 ┆ -0.242775 │
│          ┆          ┆ 39         ┆ 489       ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …        ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 3        ┆ 12       ┆ -1775.2608 ┆ -1775.269 ┆ … ┆ -0.078144 ┆ -0.087104 ┆ -0.087674 ┆ -0.155744 │
│          ┆          ┆ 05         ┆ 743       ┆   ┆           ┆           ┆           ┆           │
│ 4        ┆ 12       ┆ -1814.5448 ┆ -1814.553 ┆ … ┆ -0.077692 ┆ -0.087091 ┆ -0.088991 ┆ -0.010116 │
│          ┆          ┆ 14         ┆ 764       ┆   ┆           ┆           ┆           ┆           │
│ 5        ┆ 12       ┆ -1927.5776 ┆ -1927.587 ┆ … ┆ -0.078492 ┆ -0.086451 ┆ -0.087795 ┆ -0.04161  │
│          ┆          ┆ 54         ┆ 112       ┆   ┆           ┆           ┆           ┆           │
│ 19       ┆ 12       ┆ -1814.5423 ┆ -1814.551 ┆ … ┆ -0.079794 ┆ -0.088365 ┆ -0.090207 ┆ -0.361206 │
│          ┆          ┆ 29         ┆ 514       ┆   ┆           ┆           ┆           ┆           │
│ 20       ┆ 12       ┆ -1888.2900 ┆ -1888.298 ┆ … ┆ -0.076616 ┆ -0.0868   ┆ -0.08797  ┆ -1.174656 │
│          ┆          ┆ 27         ┆ 794       ┆   ┆           ┆           ┆           ┆           │
└──────────┴──────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
column_group = "pyridone"
column_fix = "backbone"
columns_feat = [column for column in df.columns if "zero" in column]
column_target = "beta_av_logit"

In [5]:
import numpy as np
from sklearn.linear_model import Lasso
from sklearn.metrics import root_mean_squared_error
from sklearn.preprocessing import StandardScaler

df_train_val_preds = []
df_test_preds = []
df_coefs = []

"""
Outer cross-validation
"""
groups_test = df[column_group].unique(maintain_order=True)

for group_test in groups_test:
    print(f"group_test: {group_test}")
    
    df_train_val = df.filter(pl.col(column_group) != group_test)
    df_test = df.filter(pl.col(column_group) == group_test)
    
    """
    Recursive feature elimination (RFE)
    """
    columns_rfe = columns_feat.copy()
    
    while len(columns_rfe) > 4:
        n_features = len(columns_rfe)
        print(f"n_features: {n_features}")
        
        X_train_val = df_train_val.select(columns_rfe).to_numpy()
        y_train_val = df_train_val.select(column_target).to_numpy()
        X_test = df_test.select(columns_rfe).to_numpy()
        y_test = df_test.select(column_target).to_numpy()
        
        ss_X = StandardScaler()
        ss_y = StandardScaler()
        
        X_train_val_ = ss_X.fit_transform(X_train_val)
        y_train_val_ = ss_y.fit_transform(y_train_val)
        X_test_ = ss_X.transform(X_test)
        y_test_ = ss_y.transform(y_test)
        
        """
        Hyperparameter optimization
        """
        alpha = 1.0
        
        for i in range(-1, -3, -1):
            rmses = {}
            
            for j in range(-9, 10):
                y_val_preds_ = []
                y_val_trues_ = []
                
                """
                Inner cross-validation
                """
                groups_val = df_train_val[column_group].unique(maintain_order=True)
                
                for group_val in groups_val:
                    df_train = df_train_val.filter(pl.col(column_group) != group_val)
                    df_val = df_train_val.filter(pl.col(column_group) == group_val)
                    
                    X_train = df_train.select(columns_rfe).to_numpy()
                    y_train = df_train.select(column_target).to_numpy()
                    X_val = df_val.select(columns_rfe).to_numpy()
                    y_val = df_val.select(column_target).to_numpy()
                    
                    X_train_ = ss_X.transform(X_train)
                    y_train_ = ss_y.transform(y_train)
                    X_val_ = ss_X.transform(X_val)
                    y_val_ = ss_y.transform(y_val)
                    
                    model = Lasso(alpha + j * 10**i, max_iter=5000)
                    model.fit(X_train_, y_train_)
                    
                    y_val_pred_ = model.predict(X_val_).reshape(-1, 1)
                    y_val_preds_.append(y_val_pred_)
                    y_val_trues_.append(y_val_)
                
                y_val_preds_ = np.concatenate(y_val_preds_)
                y_val_trues_ = np.concatenate(y_val_trues_)
                rmses[j] = root_mean_squared_error(y_val_trues_, y_val_preds_)
            
            j_min = min(rmses, key=rmses.get)
            alpha += j_min * 10**i
        
        """
        Refit with the best hyperparameter
        """
        model = Lasso(alpha, max_iter=5000)
        model.fit(X_train_val_, y_train_val_)
        
        """
        Store data
        """
        y_train_val_pred_ = model.predict(X_train_val_).reshape(-1, 1)
        y_train_val_pred = ss_y.inverse_transform(y_train_val_pred_)
        df_train_val_pred = pl.DataFrame(
            {
                f"{column_group}_test": group_test,
                "n_features": n_features,
                column_group: df_train_val[column_group],
                column_fix: df_train_val[column_fix],
                column_target: df_train_val[column_target],
                f"{column_target}_pred": y_train_val_pred.ravel()
            }
        )
        df_train_val_preds.append(df_train_val_pred)
        
        y_test_pred_ = model.predict(X_test_).reshape(-1, 1)
        y_test_pred = ss_y.inverse_transform(y_test_pred_)
        df_test_pred = pl.DataFrame(
            {
                f"{column_group}_test": group_test,
                "n_features": n_features,
                column_fix: df_test[column_fix],
                column_target: df_test[column_target],
                f"{column_target}_pred": y_test_pred.ravel()
            }
        )
        df_test_preds.append(df_test_pred)
        
        coef = model.coef_
        df_coef = (
            pl.DataFrame(coef.reshape(1, -1), schema=columns_rfe)
            .with_columns(
                pl.lit(group_test).alias(f"{column_group}_test"),
                pl.lit(n_features).alias("n_features"),
                pl.lit(alpha).alias("alpha"),
            )
            .select([f"{column_group}_test", "n_features", "alpha"] + columns_rfe)
        )
        df_coefs.append(df_coef)
        
        """
        Feature elimination
        """
        coef_abs = np.abs(coef)
        index_eliminate = np.where(coef_abs == np.min(coef_abs))[0]
        columns_rfe = [column for i, column in enumerate(columns_rfe) if i not in index_eliminate]

group_test: 0
n_features: 51
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 1
n_features: 51
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 2
n_features: 51
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 3
n_features: 51
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 4
n_features: 51
n_features: 16
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 5
n_features: 51
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 6
n_features: 51
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 7
n_features: 51
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 8
n_features: 51
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 9
n_features: 51
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 10
n_features: 51
n_features: 20
n_features: 19
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 11
n_features: 51
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5
group_test: 12
n_features: 51
n_features: 18
n_features: 17
n_features: 16
n_features: 15
n_features: 14
n_features: 13
n_features: 12
n_features: 11
n_features: 10
n_features: 9
n_features: 8
n_features: 7
n_features: 6
n_features: 5

In [6]:
df_train_val_preds = pl.concat(df_train_val_preds, how="vertical_relaxed")
df_test_preds = pl.concat(df_test_preds, how="vertical_relaxed")
df_coefs = pl.concat(df_coefs, how="diagonal_relaxed")

In [7]:
df_train_val_preds

shape: (14_688, 6)
┌───────────────┬────────────┬──────────┬──────────┬───────────────┬────────────────────┐
│ pyridone_test ┆ n_features ┆ pyridone ┆ backbone ┆ beta_av_logit ┆ beta_av_logit_pred │
│ ---           ┆ ---        ┆ ---      ┆ ---      ┆ ---           ┆ ---                │
│ i32           ┆ i32        ┆ i64      ┆ i64      ┆ f64           ┆ f64                │
╞═══════════════╪════════════╪══════════╪══════════╪═══════════════╪════════════════════╡
│ 0             ┆ 51         ┆ 1        ┆ 0        ┆ 0.56851       ┆ 0.313249           │
│ 0             ┆ 51         ┆ 1        ┆ 1        ┆ 0.577178      ┆ 0.505691           │
│ 0             ┆ 51         ┆ 1        ┆ 2        ┆ 0.53889       ┆ 0.388622           │
│ 0             ┆ 51         ┆ 1        ┆ 3        ┆ 0.85113       ┆ 0.412173           │
│ 0             ┆ 51         ┆ 1        ┆ 4        ┆ 0.637598      ┆ 0.43252            │
│ …             ┆ …          ┆ …        ┆ …        ┆ …             ┆ …                  │
│ 12            ┆ 5          ┆ 11       ┆ 3        ┆ -0.486342     ┆ -0.505023          │
│ 12            ┆ 5          ┆ 11       ┆ 4        ┆ -0.441697     ┆ -0.530778          │
│ 12            ┆ 5          ┆ 11       ┆ 5        ┆ 0.134649      ┆ -0.010665          │
│ 12            ┆ 5          ┆ 11       ┆ 19       ┆ -0.707688     ┆ -0.488503          │
│ 12            ┆ 5          ┆ 11       ┆ 20       ┆ -1.43681      ┆ -0.976209          │
└───────────────┴────────────┴──────────┴──────────┴───────────────┴────────────────────┘

In [8]:
df_test_preds

shape: (1_224, 5)
┌───────────────┬────────────┬──────────┬───────────────┬────────────────────┐
│ pyridone_test ┆ n_features ┆ backbone ┆ beta_av_logit ┆ beta_av_logit_pred │
│ ---           ┆ ---        ┆ ---      ┆ ---           ┆ ---                │
│ i32           ┆ i32        ┆ i64      ┆ f64           ┆ f64                │
╞═══════════════╪════════════╪══════════╪═══════════════╪════════════════════╡
│ 0             ┆ 51         ┆ 0        ┆ 0.055549      ┆ 0.154508           │
│ 0             ┆ 51         ┆ 1        ┆ 0.061619      ┆ 0.03908            │
│ 0             ┆ 51         ┆ 2        ┆ -0.086761     ┆ -0.006642          │
│ 0             ┆ 51         ┆ 3        ┆ -0.086245     ┆ 0.034357           │
│ 0             ┆ 51         ┆ 4        ┆ -0.242775     ┆ 0.031064           │
│ …             ┆ …          ┆ …        ┆ …             ┆ …                  │
│ 12            ┆ 5          ┆ 3        ┆ -0.155744     ┆ -0.230622          │
│ 12            ┆ 5          ┆ 4        ┆ -0.010116     ┆ -0.246425          │
│ 12            ┆ 5          ┆ 5        ┆ -0.04161      ┆ 0.37933            │
│ 12            ┆ 5          ┆ 19       ┆ -0.361206     ┆ -0.193415          │
│ 12            ┆ 5          ┆ 20       ┆ -1.174656     ┆ -0.978641          │
└───────────────┴────────────┴──────────┴───────────────┴────────────────────┘

In [9]:
df_coefs

shape: (153, 54)
┌───────────────┬────────────┬───────┬───────────┬───┬───────────┬──────────┬──────────┬──────────┐
│ pyridone_test ┆ n_features ┆ alpha ┆ 2_zero    ┆ … ┆ 597_zero  ┆ 602_zero ┆ 605_zero ┆ 642_zero │
│ ---           ┆ ---        ┆ ---   ┆ ---       ┆   ┆ ---       ┆ ---      ┆ ---      ┆ ---      │
│ i32           ┆ i32        ┆ f64   ┆ f64       ┆   ┆ f64       ┆ f64      ┆ f64      ┆ f64      │
╞═══════════════╪════════════╪═══════╪═══════════╪═══╪═══════════╪══════════╪══════════╪══════════╡
│ 0             ┆ 51         ┆ 0.01  ┆ -0.02593  ┆ … ┆ -0.201031 ┆ -0.0     ┆ -0.0     ┆ 0.0      │
│ 0             ┆ 19         ┆ 0.01  ┆ -0.025906 ┆ … ┆ -0.201046 ┆ null     ┆ null     ┆ null     │
│ 0             ┆ 18         ┆ 0.01  ┆ -0.047926 ┆ … ┆ -0.188286 ┆ null     ┆ null     ┆ null     │
│ 0             ┆ 17         ┆ 0.01  ┆ -0.084195 ┆ … ┆ -0.174074 ┆ null     ┆ null     ┆ null     │
│ 0             ┆ 16         ┆ 0.01  ┆ -0.062228 ┆ … ┆ -0.113382 ┆ null     ┆ null     ┆ null     │
│ …             ┆ …          ┆ …     ┆ …         ┆ … ┆ …         ┆ …        ┆ …        ┆ …        │
│ 12            ┆ 9          ┆ 0.01  ┆ null      ┆ … ┆ null      ┆ null     ┆ null     ┆ null     │
│ 12            ┆ 8          ┆ 0.02  ┆ null      ┆ … ┆ null      ┆ null     ┆ null     ┆ null     │
│ 12            ┆ 7          ┆ 0.02  ┆ null      ┆ … ┆ null      ┆ null     ┆ null     ┆ null     │
│ 12            ┆ 6          ┆ 0.03  ┆ null      ┆ … ┆ null      ┆ null     ┆ null     ┆ null     │
│ 12            ┆ 5          ┆ 0.01  ┆ null      ┆ … ┆ null      ┆ null     ┆ null     ┆ null     │
└───────────────┴────────────┴───────┴───────────┴───┴───────────┴──────────┴──────────┴──────────┘

In [10]:
df_train_val_preds.write_parquet(f"{file}_train_val_preds.parquet")
df_test_preds.write_parquet(f"{file}_test_preds.parquet")
df_coefs.write_parquet(f"{file}_coefs.parquet")