# 0. Energy descriptor for selectivity

In [1]:
import polars as pl

df_X_beta = pl.read_csv("energy_descriptor_beta.csv").sort(["pyridone", "backbone"])
df_X_alpha = pl.read_csv("energy_descriptor_alpha.csv").sort(["pyridone", "backbone"])

In [2]:
df_X_beta

shape: (104, 54)
┌──────────┬──────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ backbone ┆ pyridone ┆ 0          ┆ 2         ┆ … ┆ 597       ┆ 602       ┆ 605       ┆ 642       │
│ ---      ┆ ---      ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ i64      ┆ i64      ┆ f64        ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞══════════╪══════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0        ┆ 0        ┆ -1542.9683 ┆ -1542.977 ┆ … ┆ -1543.059 ┆ -1543.047 ┆ -1543.056 ┆ -1543.057 │
│          ┆          ┆ 56         ┆ 051       ┆   ┆ 923       ┆ 561       ┆ 282       ┆ 803       │
│ 1        ┆ 0        ┆ -1582.2585 ┆ -1582.267 ┆ … ┆ -1582.345 ┆ -1582.337 ┆ -1582.344 ┆ -1582.345 │
│          ┆          ┆ 95         ┆ 564       ┆   ┆ 121       ┆ 505       ┆ 331       ┆ 676       │
│ 2        ┆ 0        ┆ -1700.1129 ┆ -1700.121 ┆ … ┆ -1700.199 ┆ -1700.193 ┆ -1700.200 ┆ -1700.201 │
│          ┆          ┆ 5          ┆ 83        ┆   ┆ 186       ┆ 275       ┆ 596       ┆ 959       │
│ 3        ┆ 0        ┆ -1660.8285 ┆ -1660.837 ┆ … ┆ -1660.913 ┆ -1660.907 ┆ -1660.914 ┆ -1660.915 │
│          ┆          ┆ 3          ┆ 468       ┆   ┆ 003       ┆ 208       ┆ 972       ┆ 517       │
│ 4        ┆ 0        ┆ -1700.1125 ┆ -1700.121 ┆ … ┆ -1700.196 ┆ -1700.190 ┆ -1700.198 ┆ -1700.200 │
│          ┆          ┆ 39         ┆ 489       ┆   ┆ 326       ┆ 763       ┆ 991       ┆ 632       │
│ …        ┆ …        ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 3        ┆ 12       ┆ -1775.2608 ┆ -1775.269 ┆ … ┆ -1775.345 ┆ -1775.338 ┆ -1775.347 ┆ -1775.348 │
│          ┆          ┆ 05         ┆ 743       ┆   ┆ 897       ┆ 949       ┆ 909       ┆ 479       │
│ 4        ┆ 12       ┆ -1814.5448 ┆ -1814.553 ┆ … ┆ -1814.629 ┆ -1814.622 ┆ -1814.631 ┆ -1814.633 │
│          ┆          ┆ 14         ┆ 764       ┆   ┆ 205       ┆ 506       ┆ 905       ┆ 805       │
│ 5        ┆ 12       ┆ -1927.5776 ┆ -1927.587 ┆ … ┆ -1927.666 ┆ -1927.656 ┆ -1927.664 ┆ -1927.665 │
│          ┆          ┆ 54         ┆ 112       ┆   ┆ 406       ┆ 146       ┆ 105       ┆ 45        │
│ 19       ┆ 12       ┆ -1814.5423 ┆ -1814.551 ┆ … ┆ -1814.627 ┆ -1814.622 ┆ -1814.630 ┆ -1814.632 │
│          ┆          ┆ 29         ┆ 514       ┆   ┆ 402       ┆ 123       ┆ 694       ┆ 536       │
│ 20       ┆ 12       ┆ -1888.2900 ┆ -1888.298 ┆ … ┆ -1888.374 ┆ -1888.366 ┆ -1888.376 ┆ -1888.377 │
│          ┆          ┆ 27         ┆ 794       ┆   ┆ 249       ┆ 643       ┆ 827       ┆ 997       │
└──────────┴──────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [3]:
df_X_alpha

shape: (104, 46)
┌───────┬────────┬─────┬──────────┬───┬──────────────┬──────────────┬──────────────┬──────────────┐
│ arene ┆ alkene ┆ PG  ┆ backbone ┆ … ┆ 597          ┆ 602          ┆ 605          ┆ 642          │
│ ---   ┆ ---    ┆ --- ┆ ---      ┆   ┆ ---          ┆ ---          ┆ ---          ┆ ---          │
│ i64   ┆ i64    ┆ i64 ┆ i64      ┆   ┆ f64          ┆ f64          ┆ f64          ┆ f64          │
╞═══════╪════════╪═════╪══════════╪═══╪══════════════╪══════════════╪══════════════╪══════════════╡
│ 1     ┆ 0      ┆ 0   ┆ 0        ┆ … ┆ -1543.054556 ┆ -1543.041687 ┆ -1543.047691 ┆ -1543.051549 │
│ 1     ┆ 0      ┆ 0   ┆ 1        ┆ … ┆ -1582.339731 ┆ -1582.331623 ┆ -1582.335595 ┆ -1582.339394 │
│ 1     ┆ 0      ┆ 0   ┆ 2        ┆ … ┆ -1700.19379  ┆ -1700.187398 ┆ -1700.192269 ┆ -1700.195669 │
│ 1     ┆ 0      ┆ 0   ┆ 3        ┆ … ┆ -1660.907608 ┆ -1660.901324 ┆ -1660.90678  ┆ -1660.909398 │
│ 1     ┆ 0      ┆ 0   ┆ 4        ┆ … ┆ -1700.192465 ┆ -1700.184882 ┆ -1700.190297 ┆ -1700.194342 │
│ …     ┆ …      ┆ …   ┆ …        ┆ … ┆ …            ┆ …            ┆ …            ┆ …            │
│ 1     ┆ 0      ┆ 0   ┆ 3        ┆ … ┆ -1775.340534 ┆ -1775.333067 ┆ -1775.340181 ┆ -1775.342228 │
│ 1     ┆ 0      ┆ 0   ┆ 4        ┆ … ┆ -1814.623843 ┆ -1814.616626 ┆ -1814.624161 ┆ -1814.62754  │
│ 1     ┆ 0      ┆ 0   ┆ 5        ┆ … ┆ -1927.661044 ┆ -1927.650262 ┆ -1927.655793 ┆ -1927.659174 │
│ 1     ┆ 0      ┆ 0   ┆ 19       ┆ … ┆ -1814.622022 ┆ -1814.616242 ┆ -1814.62278  ┆ -1814.626296 │
│ 1     ┆ 0      ┆ 0   ┆ 20       ┆ … ┆ -1888.370408 ┆ -1888.360761 ┆ -1888.36776  ┆ -1888.372094 │
└───────┴────────┴─────┴──────────┴───┴──────────────┴──────────────┴──────────────┴──────────────┘

In [4]:
columns_feat = df_X_alpha.drop(["arene", "alkene", "PG", "backbone", "pyridone", "0"]).columns

In [5]:
df_energy = df_X_alpha[columns_feat] - df_X_beta[columns_feat]

In [6]:
df_energy

shape: (104, 40)
┌───────────┬──────────┬──────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ 12        ┆ 21       ┆ 46       ┆ 91       ┆ … ┆ 597      ┆ 602      ┆ 605      ┆ 642      │
│ ---       ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ f64       ┆ f64      ┆ f64      ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞═══════════╪══════════╪══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ -0.000914 ┆ 0.002204 ┆ 0.001732 ┆ 0.003327 ┆ … ┆ 0.005367 ┆ 0.005874 ┆ 0.008591 ┆ 0.006254 │
│ -0.0009   ┆ 0.002456 ┆ 0.001805 ┆ 0.002909 ┆ … ┆ 0.00539  ┆ 0.005882 ┆ 0.008736 ┆ 0.006282 │
│ -0.000929 ┆ 0.002349 ┆ 0.001793 ┆ 0.002784 ┆ … ┆ 0.005396 ┆ 0.005878 ┆ 0.008327 ┆ 0.00629  │
│ -0.000935 ┆ 0.002466 ┆ 0.001916 ┆ 0.003225 ┆ … ┆ 0.005396 ┆ 0.005884 ┆ 0.008192 ┆ 0.006119 │
│ -0.000867 ┆ 0.002484 ┆ 0.001933 ┆ 0.00318  ┆ … ┆ 0.003861 ┆ 0.005881 ┆ 0.008694 ┆ 0.006291 │
│ …         ┆ …        ┆ …        ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ -0.001763 ┆ 0.002501 ┆ 0.001851 ┆ 0.003199 ┆ … ┆ 0.005363 ┆ 0.005882 ┆ 0.007728 ┆ 0.006251 │
│ -0.001706 ┆ 0.00252  ┆ 0.001867 ┆ 0.00316  ┆ … ┆ 0.005362 ┆ 0.005879 ┆ 0.007745 ┆ 0.006266 │
│ -0.001751 ┆ 0.002629 ┆ 0.001756 ┆ 0.003468 ┆ … ┆ 0.005361 ┆ 0.005884 ┆ 0.008312 ┆ 0.006275 │
│ -0.001744 ┆ 0.002359 ┆ 0.001867 ┆ 0.003998 ┆ … ┆ 0.00538  ┆ 0.005881 ┆ 0.007914 ┆ 0.00624  │
│ -0.001744 ┆ 0.002407 ┆ 0.001739 ┆ 0.003767 ┆ … ┆ 0.003841 ┆ 0.005882 ┆ 0.009066 ┆ 0.005902 │
└───────────┴──────────┴──────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

In [7]:
df_X = df_X_beta[["backbone", "pyridone"]].hstack(df_energy)

In [8]:
df_X

shape: (104, 42)
┌──────────┬──────────┬───────────┬──────────┬───┬──────────┬──────────┬──────────┬──────────┐
│ backbone ┆ pyridone ┆ 12        ┆ 21       ┆ … ┆ 597      ┆ 602      ┆ 605      ┆ 642      │
│ ---      ┆ ---      ┆ ---       ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ i64      ┆ i64      ┆ f64       ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞══════════╪══════════╪═══════════╪══════════╪═══╪══════════╪══════════╪══════════╪══════════╡
│ 0        ┆ 0        ┆ -0.000914 ┆ 0.002204 ┆ … ┆ 0.005367 ┆ 0.005874 ┆ 0.008591 ┆ 0.006254 │
│ 1        ┆ 0        ┆ -0.0009   ┆ 0.002456 ┆ … ┆ 0.00539  ┆ 0.005882 ┆ 0.008736 ┆ 0.006282 │
│ 2        ┆ 0        ┆ -0.000929 ┆ 0.002349 ┆ … ┆ 0.005396 ┆ 0.005878 ┆ 0.008327 ┆ 0.00629  │
│ 3        ┆ 0        ┆ -0.000935 ┆ 0.002466 ┆ … ┆ 0.005396 ┆ 0.005884 ┆ 0.008192 ┆ 0.006119 │
│ 4        ┆ 0        ┆ -0.000867 ┆ 0.002484 ┆ … ┆ 0.003861 ┆ 0.005881 ┆ 0.008694 ┆ 0.006291 │
│ …        ┆ …        ┆ …         ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …        │
│ 3        ┆ 12       ┆ -0.001763 ┆ 0.002501 ┆ … ┆ 0.005363 ┆ 0.005882 ┆ 0.007728 ┆ 0.006251 │
│ 4        ┆ 12       ┆ -0.001706 ┆ 0.00252  ┆ … ┆ 0.005362 ┆ 0.005879 ┆ 0.007745 ┆ 0.006266 │
│ 5        ┆ 12       ┆ -0.001751 ┆ 0.002629 ┆ … ┆ 0.005361 ┆ 0.005884 ┆ 0.008312 ┆ 0.006275 │
│ 19       ┆ 12       ┆ -0.001744 ┆ 0.002359 ┆ … ┆ 0.00538  ┆ 0.005881 ┆ 0.007914 ┆ 0.00624  │
│ 20       ┆ 12       ┆ -0.001744 ┆ 0.002407 ┆ … ┆ 0.003841 ┆ 0.005882 ┆ 0.009066 ┆ 0.005902 │
└──────────┴──────────┴───────────┴──────────┴───┴──────────┴──────────┴──────────┴──────────┘

# 1. Experimental selectivity

In [9]:
df_y = pl.read_excel("combined.xlsx").sort(["pyridone", "backbone"])

In [10]:
df_y

shape: (104, 17)
┌───────┬────────┬─────┬──────────┬───┬───────────┬───────────┬────────────┬────────────┐
│ arene ┆ alkene ┆ PG  ┆ backbone ┆ … ┆ all_av    ┆ alpha_dev ┆ beta_dev   ┆ all_dev    │
│ ---   ┆ ---    ┆ --- ┆ ---      ┆   ┆ ---       ┆ ---       ┆ ---        ┆ ---        │
│ i64   ┆ i64    ┆ i64 ┆ i64      ┆   ┆ f64       ┆ f64       ┆ f64        ┆ f64        │
╞═══════╪════════╪═════╪══════════╪═══╪═══════════╪═══════════╪════════════╪════════════╡
│ 0     ┆ 0      ┆ 0   ┆ 0        ┆ … ┆ 55.502989 ┆ -0.909983 ┆ -4.354556  ┆ -5.264539  │
│ 0     ┆ 0      ┆ 0   ┆ 1        ┆ … ┆ 55.53828  ┆ 0.53966   ┆ 0.099503   ┆ 0.639163   │
│ 0     ┆ 0      ┆ 0   ┆ 2        ┆ … ┆ 51.260355 ┆ -0.065254 ┆ -1.449871  ┆ -1.515125  │
│ 0     ┆ 0      ┆ 0   ┆ 3        ┆ … ┆ 51.481642 ┆ -0.569467 ┆ -5.711042  ┆ -6.280509  │
│ 0     ┆ 0      ┆ 0   ┆ 4        ┆ … ┆ 47.283738 ┆ 0.489209  ┆ 5.191751   ┆ 5.68096    │
│ …     ┆ …      ┆ …   ┆ …        ┆ … ┆ …         ┆ …         ┆ …          ┆ …          │
│ 0     ┆ 0      ┆ 0   ┆ 3        ┆ … ┆ 49.698073 ┆ -1.08966  ┆ -10.756706 ┆ -11.846365 │
│ 0     ┆ 0      ┆ 0   ┆ 4        ┆ … ┆ 53.489722 ┆ 0.498176  ┆ 5.875049   ┆ 6.373225   │
│ 0     ┆ 0      ┆ 0   ┆ 5        ┆ … ┆ 50.13507  ┆ -0.204893 ┆ -10.588558 ┆ -10.79345  │
│ 0     ┆ 0      ┆ 0   ┆ 19       ┆ … ┆ 44.405593 ┆ 0.492666  ┆ 6.159244   ┆ 6.65191    │
│ 0     ┆ 0      ┆ 0   ┆ 20       ┆ … ┆ 26.364215 ┆ -0.176888 ┆ -1.565712  ┆ -1.7426    │
└───────┴────────┴─────┴──────────┴───┴───────────┴───────────┴────────────┴────────────┘

In [11]:
df_y = df_y[["pyridone", "backbone", "alpha_av", "beta_av"]]

In [12]:
df_y

shape: (104, 4)
┌──────────┬──────────┬──────────┬───────────┐
│ pyridone ┆ backbone ┆ alpha_av ┆ beta_av   │
│ ---      ┆ ---      ┆ ---      ┆ ---       │
│ i64      ┆ i64      ┆ f64      ┆ f64       │
╞══════════╪══════════╪══════════╪═══════════╡
│ 0        ┆ 0        ┆ 4.114632 ┆ 51.388357 │
│ 0        ┆ 1        ┆ 3.998281 ┆ 51.539999 │
│ 0        ┆ 2        ┆ 3.428027 ┆ 47.832328 │
│ 0        ┆ 3        ┆ 3.636433 ┆ 47.845209 │
│ 0        ┆ 4        ┆ 3.323485 ┆ 43.960253 │
│ …        ┆ …        ┆ …        ┆ …         │
│ 12       ┆ 3        ┆ 3.583822 ┆ 46.114252 │
│ 12       ┆ 4        ┆ 3.742613 ┆ 49.74711  │
│ 12       ┆ 5        ┆ 1.175172 ┆ 48.959898 │
│ 12       ┆ 19       ┆ 3.338815 ┆ 41.066778 │
│ 12       ┆ 20       ┆ 2.762772 ┆ 23.601443 │
└──────────┴──────────┴──────────┴───────────┘

In [13]:
df_y = df_y.with_columns((pl.col("beta_av") / pl.col("alpha_av")).log().alias("beta_alpha"))

In [14]:
df_y

shape: (104, 5)
┌──────────┬──────────┬──────────┬───────────┬────────────┐
│ pyridone ┆ backbone ┆ alpha_av ┆ beta_av   ┆ beta_alpha │
│ ---      ┆ ---      ┆ ---      ┆ ---       ┆ ---        │
│ i64      ┆ i64      ┆ f64      ┆ f64       ┆ f64        │
╞══════════╪══════════╪══════════╪═══════════╪════════════╡
│ 0        ┆ 0        ┆ 4.114632 ┆ 51.388357 ┆ 2.524862   │
│ 0        ┆ 1        ┆ 3.998281 ┆ 51.539999 ┆ 2.556494   │
│ 0        ┆ 2        ┆ 3.428027 ┆ 47.832328 ┆ 2.635717   │
│ 0        ┆ 3        ┆ 3.636433 ┆ 47.845209 ┆ 2.576968   │
│ 0        ┆ 4        ┆ 3.323485 ┆ 43.960253 ┆ 2.582272   │
│ …        ┆ …        ┆ …        ┆ …         ┆ …          │
│ 12       ┆ 3        ┆ 3.583822 ┆ 46.114252 ┆ 2.554692   │
│ 12       ┆ 4        ┆ 3.742613 ┆ 49.74711  ┆ 2.587168   │
│ 12       ┆ 5        ┆ 1.175172 ┆ 48.959898 ┆ 3.729587   │
│ 12       ┆ 19       ┆ 3.338815 ┆ 41.066778 ┆ 2.509583   │
│ 12       ┆ 20       ┆ 2.762772 ┆ 23.601443 ┆ 2.145073   │
└──────────┴──────────┴──────────┴───────────┴────────────┘

# 2. Dataset for selectivity

In [15]:
df = df_X.join(
    df_y[["backbone", "pyridone", "beta_alpha"]],
    on=["backbone", "pyridone"],
    how="left",
    maintain_order="left"
)

In [16]:
df

shape: (104, 43)
┌──────────┬──────────┬───────────┬──────────┬───┬──────────┬──────────┬──────────┬────────────┐
│ backbone ┆ pyridone ┆ 12        ┆ 21       ┆ … ┆ 602      ┆ 605      ┆ 642      ┆ beta_alpha │
│ ---      ┆ ---      ┆ ---       ┆ ---      ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---        │
│ i64      ┆ i64      ┆ f64       ┆ f64      ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64        │
╞══════════╪══════════╪═══════════╪══════════╪═══╪══════════╪══════════╪══════════╪════════════╡
│ 0        ┆ 0        ┆ -0.000914 ┆ 0.002204 ┆ … ┆ 0.005874 ┆ 0.008591 ┆ 0.006254 ┆ 2.524862   │
│ 1        ┆ 0        ┆ -0.0009   ┆ 0.002456 ┆ … ┆ 0.005882 ┆ 0.008736 ┆ 0.006282 ┆ 2.556494   │
│ 2        ┆ 0        ┆ -0.000929 ┆ 0.002349 ┆ … ┆ 0.005878 ┆ 0.008327 ┆ 0.00629  ┆ 2.635717   │
│ 3        ┆ 0        ┆ -0.000935 ┆ 0.002466 ┆ … ┆ 0.005884 ┆ 0.008192 ┆ 0.006119 ┆ 2.576968   │
│ 4        ┆ 0        ┆ -0.000867 ┆ 0.002484 ┆ … ┆ 0.005881 ┆ 0.008694 ┆ 0.006291 ┆ 2.582272   │
│ …        ┆ …        ┆ …         ┆ …        ┆ … ┆ …        ┆ …        ┆ …        ┆ …          │
│ 3        ┆ 12       ┆ -0.001763 ┆ 0.002501 ┆ … ┆ 0.005882 ┆ 0.007728 ┆ 0.006251 ┆ 2.554692   │
│ 4        ┆ 12       ┆ -0.001706 ┆ 0.00252  ┆ … ┆ 0.005879 ┆ 0.007745 ┆ 0.006266 ┆ 2.587168   │
│ 5        ┆ 12       ┆ -0.001751 ┆ 0.002629 ┆ … ┆ 0.005884 ┆ 0.008312 ┆ 0.006275 ┆ 3.729587   │
│ 19       ┆ 12       ┆ -0.001744 ┆ 0.002359 ┆ … ┆ 0.005881 ┆ 0.007914 ┆ 0.00624  ┆ 2.509583   │
│ 20       ┆ 12       ┆ -0.001744 ┆ 0.002407 ┆ … ┆ 0.005882 ┆ 0.009066 ┆ 0.005902 ┆ 2.145073   │
└──────────┴──────────┴───────────┴──────────┴───┴──────────┴──────────┴──────────┴────────────┘

In [17]:
df.write_parquet("dataset_selectivity.parquet")